// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUJbmzzUmejLfpxGTejWHDr7CVnhkRmo',
    appId: '1:288969786881:web:2342875f48315133d5a200',
    messagingSenderId: '288969786881',
    projectId: 'bankapp-29f1b',
    authDomain: 'bankapp-29f1b.firebaseapp.com',
    storageBucket: 'bankapp-29f1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyPgzU10GQt-Ilo6kfualKlRtW8JPaep4',
    appId: '1:288969786881:android:b7313e5d8865ab5dd5a200',
    messagingSenderId: '288969786881',
    projectId: 'bankapp-29f1b',
    storageBucket: 'bankapp-29f1b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXUJbmzzUmejLfpxGTejWHDr7CVnhkRmo',
    appId: '1:288969786881:web:e9f18687af34bb19d5a200',
    messagingSenderId: '288969786881',
    projectId: 'bankapp-29f1b',
    authDomain: 'bankapp-29f1b.firebaseapp.com',
    storageBucket: 'bankapp-29f1b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmrx4X2kdT8i-wdeHkDYphJb1xoq-PB0M',
    appId: '1:288969786881:ios:5c3d26f3c896bd58d5a200',
    messagingSenderId: '288969786881',
    projectId: 'bankapp-29f1b',
    storageBucket: 'bankapp-29f1b.firebasestorage.app',
    iosBundleId: 'com.example.loginWelcome',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmrx4X2kdT8i-wdeHkDYphJb1xoq-PB0M',
    appId: '1:288969786881:ios:366f1d015a14aa90d5a200',
    messagingSenderId: '288969786881',
    projectId: 'bankapp-29f1b',
    storageBucket: 'bankapp-29f1b.firebasestorage.app',
    iosBundleId: 'com.jeffer.loginWelcome',
  );

}